// <auto-generated />
using System;
using Investimentos.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Investimentos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Investimentos.Api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("FrequenciaMovimentacoes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PerfilRiscoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PrefereLiquidez")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SaldoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PerfilRiscoId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Investimentos.Api.Models.PerfilRisco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PontuacaoMaxima")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PontuacaoMinima")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PerfisRisco");
                });

            modelBuilder.Entity("Investimentos.Api.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LiquidezImediata")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PerfilRiscoRecomendado")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrazoMinimoDias")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Rentabilidade")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Risco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorMinimoInvestimento")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Investimentos.Api.Models.Simulacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataSimulacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RentabilidadeEfetiva")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("TempoRespostaMs")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorInvestido")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Simulacoes");
                });

            modelBuilder.Entity("Investimentos.Api.Models.TelemetriaRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataChamada")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetodoHttp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeServico")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TempoRespostaMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NomeServico", "DataChamada");

                    b.ToTable("TelemetriaRegistros");
                });

            modelBuilder.Entity("Investimentos.Api.Models.Cliente", b =>
                {
                    b.HasOne("Investimentos.Api.Models.PerfilRisco", "PerfilRisco")
                        .WithMany("Clientes")
                        .HasForeignKey("PerfilRiscoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PerfilRisco");
                });

            modelBuilder.Entity("Investimentos.Api.Models.Simulacao", b =>
                {
                    b.HasOne("Investimentos.Api.Models.Cliente", "Cliente")
                        .WithMany("Simulacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Investimentos.Api.Models.Produto", "Produto")
                        .WithMany("Simulacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Investimentos.Api.Models.Cliente", b =>
                {
                    b.Navigation("Simulacoes");
                });

            modelBuilder.Entity("Investimentos.Api.Models.PerfilRisco", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("Investimentos.Api.Models.Produto", b =>
                {
                    b.Navigation("Simulacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
